# Navigation Links
main:
  - name: People
    url: people
    weight: 10  
  - name: Projects
    url: project
    weight: 20
  - name: Blog
    url: blog
    weight: 30
  - name: Publications 
    url: publication
    weight: 40
