# SITE SETUP

# Appearance
appearance:
  theme_day: minimal
  font: Cyberpunk
  font_size: XL

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'City Modelling Lab'
    description: 'The City Modelling Lab is a collaboration between the University College London, Arup and the University of ZÃ¼rich to foster innovations that better enable city decision makers to make the changes required to tackle pressing global challenges such as social inequality and climate change.'
    twitter: ''
  analytics:
    google_analytics: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''

# Site header
header:
  navbar:
    enable: true
    align: r
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: false

# Site footer
footer:
  copyright:
    notice: 'Copyright {year} City Modelling Lab. All rights reserved.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false
  
# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-gb

# Site features
features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
      - python
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
  map:
    provider: 'openstreetmap'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: "2006"
  citation_style: harvard
