# Convert Bibtex publications to Markdown-based webpages
name: Import Publications From Bibtex

# Require permission to create a PR
permissions:
  contents: write
  pull-requests: write

# Run workflow when a `.bib` file is added or updated
on:
  push:
    branches:
      - main
    paths: ['data/publications.bib']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugoblox:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install academic==0.10.0
      - name: Run Academic (Bibtex To Markdown Converter)
        if: ${{ hashFiles('data/publications.bib') != '' }}
        run: academic import data/publications.bib content/publication/ --compact --overwrite
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/publication
          if ! git diff --staged --quiet; then
            git commit -m "content: import publications from Bibtex"
            git push origin HEAD:${GITHUB_REF}
          else
            echo "No changes to commit"
          fi


      # - name: Create Pull Request
      #   # Set ID for `Check outputs` stage
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     commit-message: 'content: import publications from Bibtex'
      #     title: Import latest publications
      #     body: |
      #       Import the latest publications from `publications.bib` to `content/publication/`.
      #       [View Documentation](https://github.com/GetRD/academic-file-converter)
      #     base: main
      #     labels: automated-pr, content
      #     branch: hugoblox-import-publications
      #     delete-branch: true
      # - name: Check outputs
      #   if: ${{ steps.cpr.outputs.pull-request-number }}
      #   run: |
      #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
      #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"